//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLayer
{
    using System;
    using System.Collections.Generic;

    public partial class ChatRoom
    {
        public int Id { get; set; }
        public string CRName { get; set; }
        public string CRPassword { get; set; }
        public string CRTheme { get; set; }
        public bool CRDeleted { get; set; }
        public bool CRActive { get; set; }
    }
}
